TBBETA-466: Connect clinic service to remote Dynamo DB table (#23)
* TBBETA-466: connect clinic service lambda to local and remote DB based on BRANCH env variable

* create build script for typescript

* fix duplicate lines error

* fix sonarcloud issues

* undo changes to clinic-service-deploy yaml

* run deploy workflow on push

* run deploy workflow on push

* add step to install yarn dependencies

* fix ref to build folder

* update zip command

* update zip command

* setup lambda to run in aws

* Create windows-compatible test script & fix start script in clinic service

* Deploy clinic service non-dev node modules to S3 in pipeline

* Fix build step in clinic service pipeline

* Fix build step in clinic service pipeline

* Fix zip step in clinic service pipeline

* Fix zip step in clinic service pipeline

* Fix create package.json step in clinic service pipeline

* Test syncing full node modules to s3

* Fix zip steps in clinic service pipeline

* Update clinic service test deployment pipeline to mirror dev pipeline

* Add push trigger for testing

* Add push trigger for testing

* Revert "Add push trigger for testing"

This reverts commit 47dd2a9a87d99cbafe2ccfa62ee7cacf7f01fb73.

* Revert "Add push trigger for testing"

This reverts commit ccbd9f66ce98a255b8ba422e397ec03dfffd6361.

* Remove push triggers

* edit build script

* Move serverless packages to dev dependencies

* Move script for zipping node modules from inline to separate file

* Fix zip-node-modules script

* Implement correct lambda layer folder structure into pipeline

* Fix secret names in dev deployment pipeline

* update db name

* fixed failing unit tests

* updated configutation unit test

* Move zip-node-modules to .github/scripts

* Fix zip-node-modules script file path

* Remove module exports from zip-node-modules

* Add update lambda code step to deployment pipeline

* Fix script step in deployment pipeline

* Insert comments into zip-node-modules

* Fix script step in deployment pipeline

* Log script in console for testing

* Log script in console for testing

* Add const keyword to fs require

* Print files in .github folder

* Fix printing files

* Print script contents

* Run script

* Wrap zip-node-modules.js contents in module.export

* Remove push triggers, update dev deployment pipeline to mirror test

* Add push trigger to dev pipeline

* Revert "Add push trigger to dev pipeline"

This reverts commit 49ca5fb44811f3a5e4602dcb8f66e9aa754323cd.

* Fix import in getPetsClinic

* Create draft unit tests for getPetsClinic, getPetsClinics, PetsClinicService

* deploy clinic service to dev

* upload swagger json

* swagger integrations

* fix failing dev pipeline

* fix failing dev pipeline

* fix failing dev pipeline

* retrieve lambda URIs from sm

* bump up next version to fix vulnerability

* added unit tests

* removed unused imports

* Create pipeline template to deploy UI

* Update app dev deploy pipeline to use template

* Fix jobs syntax in app-deploy-dev

* Inherit secrets in app-deploy-dev from template workflow

* Update app test deploy pipeline to use template

* update dependencies

* Remove push triggers

* Create pipeline template to deploy clinic service

* Update clinic service deploy pipelines to use template

* Fix template file paths

* babel parser fix

* Remove build-related steps to test clinic service deployment

* Wrap swagger-integrations scripts in module.export to fix 'script is not a function' TypeError

* Remove context from script call in clinic-service-deploy

* Uncomment build-related steps, remove push triggers

* Fix presets in .babelrc to run unit tests correctly:
- error described here: https://github.com/babel/babel/issues/16754
- followed this solution to resolve: https://github.com/babel/babel/issues/16754#issuecomment-2315362492

* Import ScanCommand from lib-dynamodb instead of client-dynamodb in PetsClinicDAO:
- issue & solution described here: https://github.com/aws/aws-sdk-js-v3/issues/3374#issuecomment-1055739192

* Fix DAO unit test

* Lock typescript @5.5.4 in clinic-service:
- error described here: https://github.com/LeDDGroup/typescript-transform-paths/issues/266

* Add push triggers to test deployment pipelines

* Restore previous build-related steps in clinic-service deployment pipeline

* Remove push triggers

* Move environment-specific caller workflows to /workflows/env

---------

Co-authored-by: Will Tipper <will.tipper@hotmail.co.uk>