Sprint 0 Release  (#17)
* adding ts-jest

* Add yarn audit to app-ci & app-cd

* Add upload artifact step to add-cd.yaml

* Correct upload artifact step

* Change build working directory step, rename deploy job

* Update babelrc to resolve build error:
- error when build triggered: https://nextjs.org/docs/messages/babel-font-loader-conflict
- solution: https://nextjs.org/docs/pages/building-your-application/configuring/babel

* Update babelrc to resolve build error:
- error & solution: https://nextjs.org/docs/messages/swc-disabled

* Fix build path in app-cd.yaml

* Create deploy job in app-cd.yaml, rename previous deploy job to build

* Add S3 sync step to app-cd.yaml deploy job

* Add download artifact step to app-cd.yaml deploy job

* Add AWS role to app-cd.yaml, add .env to gitignore

* Update app-cd.yaml to use GitHub secrets

* Update app-cd.yaml to use debug mode in S3 sync step

* Revert "Update app-cd.yaml to use debug mode in S3 sync step"

This reverts commit 9f0bc04ade4d531294632a590ebfc50ea1e16831.

* Add sse flag to s3 sync step in app-cd.yaml

* Revert "Add sse flag to s3 sync step in app-cd.yaml"

This reverts commit 3a511e7706e9c426f686de2b1d868b13b0e92e1a.

* Add sse flag with kms to s3 sync step in app-cd.yaml

* Add kms key id to s3 sync step in app-cd.yaml

* Delete images in app/pets-ui/public/

* Delete old S3 Sync action from add-cd.yaml

* Update assumed role secret name in app-cd.yaml

* Create CD pipeline for clinic-service

* Add push trigger to CD pipeline for testing

* Comment out unit test step from CD pipeline:
(unit tests have not been merged yet)

* building core logic and unit tested dao

* Comment out linting step from CD pipeline:
(linter has not been added yet)

* Update handler file location in deploy job

* Revert "Add push trigger to CD pipeline for testing"

This reverts commit 2e675e22d906d3f15273a7f7a71d0d79ce971e29.

* Rename clinic-service-cd to clinic-service-pr-checks

* Create separate deploy workflow for clinic-service

* Remove deploy steps from clinic-service-pr-checks

* Add unit testing into clinic-service-pr-checks

* Fix trigger in clinic-service-deploy

* Add push trigger to clinic service pipelines for testing

* Revert "Add push trigger to clinic service pipelines for testing"

This reverts commit f953106f170898e515ae55cbd8ef04d6fcc435d1.

* Update pr checks to run on prs to all branches

* Create separate deploy workflow for ui app

* Rename app-cd to app-pr-checks

* Remove build and deploy steps from app-pr-checks

* Update app-ci to use working-directory

* Create clinic-service CI

* Fix trigger event in clinic-service-ci

* Zip handler file in clinic-service-deploy

* Add push trigger to clinic service pipeline for testing

* Change zip working directory in clinic-service-deploy

* Change upload working directory in clinic-service-deploy

* Fix upload path in clinic-service-deploy

* Update clinic model in model & test resources

* Update config files to render UI correctly

* Update dashboard component with new clinic model

* Revert "Add push trigger to clinic service pipeline for testing"

This reverts commit 94a18b6f525ed2dc395cfea3f88b4a9b24465d9b.

* Add push trigger to clinic service pipeline for testing

* Revert "Add push trigger to clinic service pipeline for testing"

This reverts commit b9afd62e2ff6bf089930b8f23761cc97c41dafed.

* Update IPetsClinic interface with new clinic model

* Consolidate app CD into a single job, add push trigger for testing

* Remove push trigger and unused steps in app CD

* Consolidate clinic service CD into a single job, add push trigger for testing

* Fix clinic service CD upload step

* Replace s3 sync with s3 cp in clinic service CD

* Remove push trigger and unused steps in clinic service CD

* Remove swagger.js file from gitignore scope

* Add step to upload swagger file to clinic service deployment

* Add push trigger to clinic service deployment for testing

* Correct gitignore comment & rename clinic service deployment job

* Revert "Add push trigger to clinic service deployment for testing"

This reverts commit ff8bd7e84e18b2a6cf86423fc17b5ea72858dec2.

* Add app deploy pipeline for dev environment

* Add clinic service deploy pipeline for dev environment

* Remove push triggers in dev deployment pipelines

* TBBETA-454: Update deploy pipelines to retrieve secrets from AWS Secrets Manager (#21)

* Modify app deploy workflow to use Secrets Manager

* Add push trigger to app deploy workflow for testing

* Fix environment variable names in app deploy workflow

* Fix secret name in app deploy workflow

* Rename app deploy workflow & tidy:
- Remove push trigger
- Remove commented code

* Rename clinic service deploy workflow & update to pull secrets from AWS

* Change triggers for deploy-test workflows to manual only

* Allow app deployment pipeline to access test environment secrets

* Remove push trigger in app deployment workflow

* Rename deployment workflows, use test env secrets in clinic service deployment

* Fix push trigger in clinic service deployment pipeline

* Remove push trigger in clinic service deployment pipeline

* Update clinic service deployment pipelines to deploy build folder, remove trigger to deploy on closed pr

* TBBETA-474: Convert swagger.js to swagger.json for use by API Gateway (#24)

* Add swagger-integrations script to clinic service deploy workflow:
- add swagger-integrations.js to clinic-service
- rename deploy job
- retrieve URI secrets to insert into swagger spec
- add step to run swagger-integrations script
- add push trigger for testing

* Fix build & zip steps in clinic-service deploy workflow

* Add build script to clinic-service package.json

* Revert "Add build script to clinic-service package.json"

This reverts commit b79176d74eb004fac224bd3c913fb1b2b08c53d0.

* Revert "Fix build & zip steps in clinic-service deploy workflow"

This reverts commit c7bdc57f35bbdaff7b51315e0b20b3c6d0020e6b.

* Remove deployment of build from pipeline for testing

* Fix swagger-integrations working directory in pipeline

* Add export statement to swagger-integrations

* Remove export statement from swagger-integrations

* Add console.logs for testing

* Revert "Add console.logs for testing"

This reverts commit 41947b185cfa7dfc2088e45af7528ae7b4a71abf.

* Upload swagger with integration blocks to s3

* Remove declarative keywords in script

* Modify swagger-integrations to return an object instead of a list

* Modify swagger-integrations to return a 1D array

* Deploy entire output of swagger-integrations instead of splitting

* Modify swagger-integrations to return a string

* Modify swagger-integrations to return a string

* Move swagger-integrations to inline in deploy pipeline

* Write swagger to file to upload to s3

* Convert swagger to string before uploading to s3

* Fix s3 upload working directory

* Add console log at start of script

* Add additional console logs

* Add additional console log

* Fix .split step to split on \n instead of \r\n

* Fix .split step in swagger-integrations

* Update pipeline to use fixed swagger-integrations script

* Cast swagger-integrations output to string

* Add export to script as per actions/github-script docs

* Fix syntax when running script

* Add list of uri names to script output

* Parse outputs from script into separate variables

* Initialise variables before running script

* Update script to return an object rather than a list

* Test URI replacement in swagger spec

* Fix URI replacement in swagger spec

* Insert URIs into swagger spec from secrets

* Fix inserting URIs into swagger spec from secrets

* Test if secrets are being correctly retrieved

* Test retrieving secrets using blank alias

* Test retrieving secrets using alias

* Remove alias from secrets

* Test that bucket secrets are being retrieved correctly

* Test that bucket secrets are being retrieved correctly

* Test that bucket secrets are being retrieved correctly

* Restore pipeline script

* Test combining all secrets into a single secret

* Print URI secrets during pipeline execution

* Test printing secrets to console

* Fix printing secrets to console

* Fix referencing secrets in pipeline, remove printing secrets step

* Write swagger spec to file & push to s3

* Write swagger spec to file as JSON

* Revert "Write swagger spec to file as JSON"

This reverts commit b69c3ad72477467553a381a0261981b9ed89e98f.

* Retrieve correct secrets in pipeline

* Uncomment build-related dev pipeline steps, remove push trigger

* Update test deployment pipeline to correctly deploy swagger file

* Add push trigger to test deployment pipeline

* Remove build-related steps for testing

* Revert "Remove build-related steps for testing"

This reverts commit cce0802be4e4361b1fcd5f74b59cde0f51fc23f8.

* Revert "Add push trigger to test deployment pipeline"

This reverts commit 592f3a75451a75e71650ff0d332884bb3432035c.

* Fix deploy job name in test deploy pipeline

* Fix package vulnerabilities identified in yarn audit

* Revert "Fix package vulnerabilities identified in yarn audit"

This reverts commit d520983d7273490ee0724c67028b599970c3a91f.

* Update packages to address security vulnerabilities

* Move swagger-integrations to .github/scripts

* Update swagger-integrations.js & deploy pipelines to write file inside script

* Remove build-related steps for pipeline testing

* Fix scripts folder location

* Fix script file path in deployment pipeline

* Make script file executable

* Revert to github-script action to run script

* Fix uriSecretName naming in swagger-integrations

* Split github-script over 2 lines

* Add context to swagger-integrations arguments

* Revert swagger-integrations & pipeline changes

* Fix swagger-integrations script file path

* Fix fs require line in swagger-integrations

* Fix fs require line in swagger-integrations

* Remove push triggers

* Pass context into swagger-integrations script

* Fix fs require line in swagger-integrations

* Revert "Fix fs require line in swagger-integrations"

This reverts commit 7cf62591f730369637d666ff28c922995ab94b22.

* Remove push triggers

* Remove module exports from swagger-integrations

* Create pipeline template to deploy UI

* Update app dev deploy pipeline to use template

* Fix jobs syntax in app-deploy-dev

* Inherit secrets in app-deploy-dev from template workflow

* Update app test deploy pipeline to use template

* Remove push triggers

* Create pipeline template to deploy clinic service

* Update clinic service deploy pipelines to use template

* Fix template file paths

* Remove build-related steps to test clinic service deployment

* Wrap swagger-integrations scripts in module.export to fix 'script is not a function' TypeError

* Remove context from script call in clinic-service-deploy

* Uncomment build-related steps, remove push triggers

* Move environment-specific caller workflows to /workflows/env

* TBBETA-466: Connect clinic service to remote Dynamo DB table (#23)

* TBBETA-466: connect clinic service lambda to local and remote DB based on BRANCH env variable

* create build script for typescript

* fix duplicate lines error

* fix sonarcloud issues

* undo changes to clinic-service-deploy yaml

* run deploy workflow on push

* run deploy workflow on push

* add step to install yarn dependencies

* fix ref to build folder

* update zip command

* update zip command

* setup lambda to run in aws

* Create windows-compatible test script & fix start script in clinic service

* Deploy clinic service non-dev node modules to S3 in pipeline

* Fix build step in clinic service pipeline

* Fix build step in clinic service pipeline

* Fix zip step in clinic service pipeline

* Fix zip step in clinic service pipeline

* Fix create package.json step in clinic service pipeline

* Test syncing full node modules to s3

* Fix zip steps in clinic service pipeline

* Update clinic service test deployment pipeline to mirror dev pipeline

* Add push trigger for testing

* Add push trigger for testing

* Revert "Add push trigger for testing"

This reverts commit 47dd2a9a87d99cbafe2ccfa62ee7cacf7f01fb73.

* Revert "Add push trigger for testing"

This reverts commit ccbd9f66ce98a255b8ba422e397ec03dfffd6361.

* Remove push triggers

* edit build script

* Move serverless packages to dev dependencies

* Move script for zipping node modules from inline to separate file

* Fix zip-node-modules script

* Implement correct lambda layer folder structure into pipeline

* Fix secret names in dev deployment pipeline

* update db name

* fixed failing unit tests

* updated configutation unit test

* Move zip-node-modules to .github/scripts

* Fix zip-node-modules script file path

* Remove module exports from zip-node-modules

* Add update lambda code step to deployment pipeline

* Fix script step in deployment pipeline

* Insert comments into zip-node-modules

* Fix script step in deployment pipeline

* Log script in console for testing

* Log script in console for testing

* Add const keyword to fs require

* Print files in .github folder

* Fix printing files

* Print script contents

* Run script

* Wrap zip-node-modules.js contents in module.export

* Remove push triggers, update dev deployment pipeline to mirror test

* Add push trigger to dev pipeline

* Revert "Add push trigger to dev pipeline"

This reverts commit 49ca5fb44811f3a5e4602dcb8f66e9aa754323cd.

* Fix import in getPetsClinic

* Create draft unit tests for getPetsClinic, getPetsClinics, PetsClinicService

* deploy clinic service to dev

* upload swagger json

* swagger integrations

* fix failing dev pipeline

* fix failing dev pipeline

* fix failing dev pipeline

* retrieve lambda URIs from sm

* bump up next version to fix vulnerability

* added unit tests

* removed unused imports

* Create pipeline template to deploy UI

* Update app dev deploy pipeline to use template

* Fix jobs syntax in app-deploy-dev

* Inherit secrets in app-deploy-dev from template workflow

* Update app test deploy pipeline to use template

* update dependencies

* Remove push triggers

* Create pipeline template to deploy clinic service

* Update clinic service deploy pipelines to use template

* Fix template file paths

* babel parser fix

* Remove build-related steps to test clinic service deployment

* Wrap swagger-integrations scripts in module.export to fix 'script is not a function' TypeError

* Remove context from script call in clinic-service-deploy

* Uncomment build-related steps, remove push triggers

* Fix presets in .babelrc to run unit tests correctly:
- error described here: https://github.com/babel/babel/issues/16754
- followed this solution to resolve: https://github.com/babel/babel/issues/16754#issuecomment-2315362492

* Import ScanCommand from lib-dynamodb instead of client-dynamodb in PetsClinicDAO:
- issue & solution described here: https://github.com/aws/aws-sdk-js-v3/issues/3374#issuecomment-1055739192

* Fix DAO unit test

* Lock typescript @5.5.4 in clinic-service:
- error described here: https://github.com/LeDDGroup/typescript-transform-paths/issues/266

* Add push triggers to test deployment pipelines

* Restore previous build-related steps in clinic-service deployment pipeline

* Remove push triggers

* Move environment-specific caller workflows to /workflows/env

---------

Co-authored-by: Will Tipper <will.tipper@hotmail.co.uk>

* Delete Validator constructor to fix sonarcloud issue

---------

Co-authored-by: Will Tipper <will.tipper@hotmail.co.uk>
Co-authored-by: Will <100358610+WJTipper@users.noreply.github.com>